# -*- coding: utf-8 -*-
"""Walmart_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4M1MjalpRBIXqP7DbQcQmssr8h6evlX
"""

#importing necessary libraries
import os
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
import statsmodels.api as sm
from scipy import stats
from statsmodels.tsa.seasonal import STL

df = pd.read_csv('/content/Walmart DataSet.csv')

# normalize column names (if applicable)
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
# parse date
df['date'] = pd.to_datetime(df['date'], errors='coerce')

# quick sanity
print("Rows, Columns:", df.shape)
print(df.dtypes)
print(df.head())

# 2. Feature engineering
df['date'] = df['date'].fillna(pd.to_datetime('1900-01-01')) # Fill NaT with a placeholder date
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month.astype(int)
df['month_name'] = df['date'].dt.month_name().str.slice(stop=3)
df['week'] = df['date'].dt.isocalendar().week.astype(int)
df['holiday_flag'] = df['holiday_flag'].fillna(0).astype(int) # Ensure holiday_flag is int after filling NaN

# Ensure numeric
numeric_cols = ['weekly_sales','temperature','fuel_price','cpi','unemployment']
for c in numeric_cols:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors='coerce')

# Quick summary
print("Columns present:", df.columns.tolist())
print("Missing values per column:\n", df.isna().sum())

#3. Missing value handling
#print_headline("MISSING VALUE IMPUTATION")
# Strategy: median imputation within-store for numeric fields; fallback to global median
def impute_median_by_store(df, col):
    if col not in df.columns:
        return df
    df[col] = df.groupby('store')[col].transform(lambda s: s.fillna(s.median()))
    df[col] = df[col].fillna(df[col].median())
    return df

for col in numeric_cols:
    df = impute_median_by_store(df, col)

# Holiday flag: fill missing with 0 and ensure int
if 'holiday_flag' in df.columns:
    df['holiday_flag'] = df['holiday_flag'].fillna(0).astype(int)
else:
    df['holiday_flag'] = 0

print("Missing after imputation:\n", df.isna().sum())

# 4. Outlier analysis & treatment
#print_headline("OUTLIER ANALYSIS")
# show some stats
OUT_DIR = './output' # Define OUT_DIR
os.makedirs(OUT_DIR, exist_ok=True) # Create the directory if it doesn't exist
stats_summary = df[numeric_cols].describe().transpose()
stats_summary.to_csv(os.path.join(OUT_DIR, "numeric_summary_before_outlier.csv"))
print(stats_summary)

# IQR capping per-store for weekly_sales
def cap_iqr_per_group(df, col, group_col='store'):
    def cap_series(s):
        q1 = s.quantile(0.25)
        q3 = s.quantile(0.75)
        iqr = q3 - q1
        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr
        return s.clip(lower=lower, upper=upper)
    cap_col = col + "_cap"
    df[cap_col] = df.groupby(group_col)[col].transform(cap_series)
    # fallback if any NaNs
    df[cap_col] = df[cap_col].fillna(df[col].median())
    return df

df = cap_iqr_per_group(df, 'weekly_sales', 'store')
df['log_sales'] = np.log1p(df['weekly_sales'])
df['log_sales_cap'] = np.log1p(df['weekly_sales_cap'])

print("Outlier capping done. Example ranges (capped column):")
print(df['weekly_sales_cap'].describe())

#5.Perform Exploratory Data Analysis (EDA)
#print_headline("EXPLORATORY DATA ANALYSIS (EDA)")
# a) Overall time series plot (total weekly sales across all stores)
ts = df[df['date'] != pd.to_datetime('1900-01-01')].groupby('date').agg(total_sales=('weekly_sales_cap','sum')).reset_index()
fig, ax = plt.subplots(figsize=(12,4))
ax.plot(ts['date'], ts['total_sales'])
ax.set_title("Total Weekly Sales (capped) - All Stores")
ax.set_xlabel("Date"); ax.set_ylabel("Total Weekly Sales")
#safe_savefig(fig, "timeseries_total_weekly_sales.png")

# b) Correlation heatmap among numeric vars
corr_cols = ['weekly_sales_cap','temperature','fuel_price','cpi','unemployment','holiday_flag']
corr_df = df[corr_cols].corr()
fig, ax = plt.subplots(figsize=(6,4))
sns.heatmap(corr_df, annot=True, fmt=".2f", cmap='coolwarm', ax=ax)
ax.set_title("Correlation Matrix")
#safe_savefig(fig, "corr_matrix.png")

# c) Average sales by month (seasonality view)
monthly = df.groupby('month').agg(mean_sales=('weekly_sales_cap','mean'),
                                  median_sales=('weekly_sales_cap','median'),
                                  sd=('weekly_sales_cap','std'),
                                  n=('weekly_sales_cap','count')).reset_index().sort_values('month')
monthly['se'] = monthly['sd']/np.sqrt(monthly['n'])
monthly['ci_low'] = monthly['mean_sales'] - 1.96*monthly['se']
monthly['ci_high'] = monthly['mean_sales'] + 1.96*monthly['se']
monthly.to_csv(os.path.join(OUT_DIR, "monthly_summary.csv"), index=False)

fig, ax = plt.subplots(figsize=(6,4))
ax.plot(monthly['month'], monthly['mean_sales'], marker='o')
ax.fill_between(monthly['month'], monthly['ci_low'], monthly['ci_high'], alpha=0.2)
ax.set_xticks(monthly['month'])
ax.set_title("Average Weekly Sales by Month (capped)")
ax.set_xlabel("Month"); ax.set_ylabel("Mean Weekly Sales")
#safe_savefig(fig, "avg_sales_by_month.png")

# d) Sales vs Unemployment scatter (all stores) with LOESS-like smoothing (lowess)
fig, ax = plt.subplots(figsize=(6,4))
sns.scatterplot(data=df.sample(min(len(df), 2000), random_state=1), x='unemployment', y='weekly_sales_cap', alpha=0.4, s=10, ax=ax)
# lowess from statsmodels
lowess = sm.nonparametric.lowess(df['weekly_sales_cap'], df['unemployment'], frac=0.3)
ax.plot(lowess[:,0], lowess[:,1], color='red', linewidth=2)
ax.set_title("Sales vs Unemployment (sampled points + LOWESS)")
#safe_savefig(fig, "sales_vs_unemployment_lowess.png")

# e) Top and bottom stores by mean sales
store_perf = df.groupby('store').agg(mean_sales=('weekly_sales_cap','mean'),
                                    median_sales=('weekly_sales_cap','median'),
                                    sd=('weekly_sales_cap','std'),
                                    n=('weekly_sales_cap','count')).reset_index()
store_perf['se'] = store_perf['sd']/np.sqrt(store_perf['n'])
store_perf = store_perf.sort_values('mean_sales', ascending=False)
store_perf.to_csv(os.path.join(OUT_DIR, "store_performance_summary.csv"), index=False)

fig, ax = plt.subplots(figsize=(6,4))
sns.barplot(data=store_perf.head(15), x='store', y='mean_sales', palette="Blues_d", ax=ax)
ax.set_title("Top 15 Stores by Mean Weekly Sales (capped)")
ax.set_xlabel("Store"); ax.set_ylabel("Mean Weekly Sales")
#safe_savefig(fig, "top15_stores_mean_sales.png")

# 6. Statistical analyses & tests
#print_headline("STATISTICAL ANALYSES")
#a) Test whether month has a significant effect on sales (ANOVA)
df['month_factor'] = df['month'].astype('category')
anova_model = smf.ols('weekly_sales_cap ~ C(month_factor)', data=df).fit()
anova_table = sm.stats.anova_lm(anova_model, typ=2)
print("ANOVA (month effect) table:\n", anova_table)
anova_table.to_csv(os.path.join(OUT_DIR, "anova_month_effect.csv"))

# Define global_model, cpi_model, and temp_mod
global_model = smf.ols('weekly_sales_cap ~ unemployment', data=df).fit()
df['log_cpi'] = np.log1p(df['cpi'])
cpi_model = smf.ols('weekly_sales_cap ~ log_cpi', data=df).fit()
df['temp2'] = df['temperature']**2
temp_mod = smf.ols('weekly_sales_cap ~ temperature + temp2', data=df).fit()

# 7. Insights & Summaries to file
#print_headline("GENERATE SUMMARY INSIGHTS FILES")
best_store = store_perf.iloc[0]
worst_store = store_perf.iloc[-1]
gap_abs = best_store['mean_sales'] - worst_store['mean_sales']
gap_pct = gap_abs / best_store['mean_sales'] * 100
summary_lines = [
    f"Dataset rows: {df.shape[0]}, stores: {df['store'].nunique()}",
    f"Best store (mean weekly sales, capped): Store {best_store['store']} = {best_store['mean_sales']:.2f}",
    f"Worst store (mean weekly sales, capped): Store {worst_store['store']} = {worst_store['mean_sales']:.2f}",
    f"Absolute gap (best - worst): {gap_abs:.2f}, Percent gap: {gap_pct:.2f}%",
    f"ANOVA (month) p-value: {anova_table['PR(>F)'].iloc[0] if 'PR(>F)' in anova_table.columns else 'NA'}",
    f"Global regression unemployment coef: {global_model.params.get('unemployment'):.4f}, p: {global_model.pvalues.get('unemployment'):.4f}",
    f"Global CPI elasticity (log_cpi coef): {cpi_model.params.get('log_cpi'):.4f}, p: {cpi_model.pvalues.get('log_cpi'):.4f}",
    f"Temperature linear coef: {temp_mod.params.get('temperature'):.6f}, temp^2 coef: {temp_mod.params.get('temp2'):.6f}"
]
with open(os.path.join(OUT_DIR, "analysis_summary.txt"), "w") as f:
    f.write("\n".join(summary_lines))
print("Summary written to outputs/analysis_summary.txt")
print("\n".join(summary_lines))

#PROBLEM QUESTIONS
#1a) If the weekly sales are affected by the unemployment rate, if yes - which stores are suffering the most?
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

# Load dataset
df = pd.read_csv("Walmart DataSet.csv")
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df['date'] = pd.to_datetime(df['date'], errors='coerce')

# Fill missing values with median per store
for col in ['weekly_sales','temperature','fuel_price','cpi','unemployment']:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df[col] = df.groupby('store')[col].transform(lambda x: x.fillna(x.median()))
df['log_sales'] = np.log1p(df['weekly_sales'])

# Run per-store regression and collect unemployment effects
results = []
for s, g in df.groupby('store'):   #s is store number and g is data subset for that store
    if len(g) < 20: continue
    m = smf.ols('log_sales ~ unemployment + cpi + fuel_price + temperature + holiday_flag', data=g).fit()   #statsmodel formula for ordinary least squarte regression
    results.append([s, m.params['unemployment'], m.pvalues['unemployment']])

res = pd.DataFrame(results, columns=['store','coef_unemployment','pvalue'])
res['effect'] = np.where((res['coef_unemployment']<0)&(res['pvalue']<0.05),
                         'Negative & significant','Not significant')
print("Stores most suffering from unemployment:\n")
print(res[res['effect']=='Negative & significant'].sort_values('coef_unemployment').head(10))

#1b. If the weekly sales show a seasonal trend, when and what could be the reason?
# Seasonality analysis
# Group by month

# Fill NaT values in date column with a default date before extracting month
df['date'] = df['date'].fillna(pd.to_datetime('1900-01-01'))

# Extract month from date column
df['month'] = df['date'].dt.month.astype(int)

monthly = df.groupby('month').agg(
    mean_sales=('weekly_sales','mean'),
    median_sales=('weekly_sales','median'),
    sd=('weekly_sales','std'),
    n=('weekly_sales','count')
).reset_index()

# Confidence interval
monthly['se'] = monthly['sd'] / np.sqrt(monthly['n'])
monthly['ci_low'] = monthly['mean_sales'] - 1.96 * monthly['se']
monthly['ci_high'] = monthly['mean_sales'] + 1.96 * monthly['se']

# Plot average sales by month
fig, ax = plt.subplots(figsize=(6,4))
ax.plot(monthly['month'], monthly['mean_sales'], marker='o', label='Mean Sales')
ax.fill_between(monthly['month'], monthly['ci_low'], monthly['ci_high'], color='blue', alpha=0.2)
ax.set_xticks(range(1,13))
ax.set_title("Average Weekly Sales by Month (Seasonality View)")
ax.set_xlabel("Month"); ax.set_ylabel("Mean Weekly Sales")
plt.legend()
plt.show()

#ANOVA test
df['month_factor'] = df['month'].astype('category')
anova_model = smf.ols('weekly_sales ~ C(month_factor)', data=df).fit()
anova_table = sm.stats.anova_lm(anova_model, typ=2)
print("ANOVA (month effect) table:\n", anova_table)

#1c. Does temperature affect the weekly sales in any manner?


import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
import statsmodels.formula.api as smf

# Load dataset
df = pd.read_csv("Walmart DataSet.csv")
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df['date'] = pd.to_datetime(df['date'], errors='coerce')

# Fill missing values with median per store
for col in ['weekly_sales','temperature','fuel_price','cpi','unemployment']:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df[col] = df.groupby('store')[col].transform(lambda x: x.fillna(x.median()))

# Add squared term for non-linear effect
df['temp2'] = df['temperature']**2

# Visualization
plt.figure(figsize=(6,4))
sns.scatterplot(x='temperature', y='weekly_sales', data=df.sample(2000, random_state=1), alpha=0.4, s=12)
sns.regplot(x='temperature', y='weekly_sales', data=df, scatter=False, order=2, color='red')
plt.title("Weekly Sales vs Temperature")
plt.show()

#  Regression Model
model = smf.ols("weekly_sales ~ temperature + temp2 + cpi + unemployment + fuel_price + holiday_flag", data=df).fit()
print(model.summary())

#1d. How is the Consumer Price index affecting the weekly sales of various stores?

# Run per-store regression: log_sales ~ CPI (+ controls)
results = []
for s, g in df.groupby('store'):
    if len(g) < 20: continue
    # Add log_sales column to the grouped dataframe 'g'
    g['log_sales'] = np.log1p(g['weekly_sales'])
    m = smf.ols('log_sales ~ cpi + unemployment + fuel_price + temperature + holiday_flag', data=g).fit()
    results.append([s, m.params['cpi'], m.pvalues['cpi']])

# Collect results in DataFrame
res_cpi = pd.DataFrame(results, columns=['store','coef_cpi','pvalue'])
res_cpi['effect'] = np.where((res_cpi['coef_cpi']<0)&(res_cpi['pvalue']<0.05),
                             'Negative & significant','Not significant')

# Show stores most negatively affected by CPI
print("Stores most negatively affected by CPI:\n")
print(res_cpi[res_cpi['effect']=='Negative & significant'].sort_values('coef_cpi').head(10))

# Save to CSV for reporting
res_cpi.to_csv("cpi_effects_per_store.csv", index=False)

#1e. Top performing stores according to the historical data.

# Compute store performance (mean weekly sales)
store_perf = df.groupby('store')['weekly_sales'].mean().reset_index().sort_values('weekly_sales', ascending=False)

# Display top 10 stores
print("Top 10 Performing Stores:\n")
print(store_perf.head(10))

# Plot Top 10 Stores
plt.figure(figsize=(6,4))
sns.barplot(x='store', y='weekly_sales', data=store_perf.head(10), palette="Blues_d")
plt.title("Top 10 Performing Stores (Mean Weekly Sales)")
plt.xlabel("Store")
plt.ylabel("Mean Weekly Sales")
plt.show()

#1f. The worst performing store, and how significant is the difference between the highest and lowest performing stores.

# Compute mean sales per store
store_perf = df.groupby('store')['weekly_sales'].mean().reset_index()

# Identify best and worst stores
best_store = store_perf.loc[store_perf['weekly_sales'].idxmax()]
worst_store = store_perf.loc[store_perf['weekly_sales'].idxmin()]

# Calculate sales gap
gap_abs = best_store['weekly_sales'] - worst_store['weekly_sales']
gap_pct = (gap_abs / best_store['weekly_sales']) * 100

# Print results
print(f"Best Store: {int(best_store['store'])} with mean weekly sales = {best_store['weekly_sales']:.2f}")
print(f"Worst Store: {int(worst_store['store'])} with mean weekly sales = {worst_store['weekly_sales']:.2f}")
print(f"Absolute Gap = {gap_abs:.2f}, Percent Gap = {gap_pct:.2f}%")

#2. Use predictive modeling techniques to forecast the sales for each store for the next 12 weeks.

import pandas as pd
import statsmodels.api as sm
from statsmodels.tsa.arima.model import ARIMA

# Load dataset
df = pd.read_csv("Walmart DataSet.csv")
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df['date'] = pd.to_datetime(df['date'], errors='coerce')

# Handle missing values in numeric columns (median per store)
for col in ['weekly_sales','temperature','fuel_price','cpi','unemployment']:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df[col] = df.groupby('store')[col].transform(lambda x: x.fillna(x.median()))

# Fill NaT values in date column with a placeholder date before sorting
df['date'] = df['date'].fillna(pd.to_datetime('1900-01-01'))

# Sort by store and date to ensure monotonic time series for each store
df = df.sort_values(by=['store', 'date'])

# Forecast next 12 weeks per store
forecast_results = {}

for store, g in df.groupby('store'):
    # Ensure dates are unique and sorted for the time series
    g = g.drop_duplicates(subset=['date']).sort_values('date')

    # Exclude placeholder dates for time series analysis
    g_ts = g[g['date'] != pd.to_datetime('1900-01-01')].copy()

    if len(g_ts) < 2: # Need at least two points to fit a time series model
        print(f"Store {store} has insufficient data for forecasting.")
        continue

    ts = g_ts.set_index('date')['weekly_sales']

    # Fit ARIMA model
    try:
        model = ARIMA(ts, order=(1,1,1))
        results = model.fit()

        # Forecast next 12 weeks
        forecast = results.get_forecast(steps=12)
        forecast_df = forecast.summary_frame()[['mean','mean_ci_lower','mean_ci_upper']]
        forecast_results[store] = forecast_df

        print(f"\nStore {store} - Next 12 Weeks Forecast:")
        print(forecast_df)

    except Exception as e:
        print(f"Store {store} - Model failed: {e}")

print(df['date'].head())
print(df['date'].tail())
print(df['date'].dtype)
print(df['date'].isnull().sum())
print(df['date'].is_monotonic_increasing)

#Forecast Visualization

# Function to plot forecast for a given store
def plot_store_forecast(store_id, df, forecast_results):
    # Original data
    g = df[df['store'] == store_id][['date','weekly_sales']].sort_values('date')

    # Forecasted data (last 12 weeks)
    if store_id not in forecast_results:
        print(f"No forecast available for Store {store_id}")
        return
    forecast = forecast_results[store_id]

    plt.figure(figsize=(8,6))

    # Plot historical sales
    plt.plot(g['date'], g['weekly_sales'], label='Historical Sales', color='blue')

    # Plot forecast line
    plt.plot(forecast.index, forecast['mean'], label='Forecast Sales', color='red')

    # Plot confidence interval
    plt.fill_between(forecast.index, forecast['mean_ci_lower'], forecast['mean_ci_upper'],
                     color='pink', alpha=0.3, label='Confidence Interval')

    plt.title(f"Store {store_id} - 12 Weeks Sales Forecast")
    plt.xlabel("Date")
    plt.ylabel("Weekly Sales")
    plt.legend()
    plt.show()

# ---------- Plot for Top 5 stores ----------
# Identify top 5 stores by mean sales (using the original df before any filtering for forecast)
top_stores = df.groupby('store')['weekly_sales'].mean().sort_values(ascending=False).head(5).index.tolist()

print("Plotting forecasts for the top 5 stores:", top_stores)

for store in top_stores:
    plot_store_forecast(store, df, forecast_results)

# Identify stores with non-monotonic dates
non_monotonic_stores = []
for store, g in df.groupby('store'):
    if not g['date'].is_monotonic_increasing:
        non_monotonic_stores.append(store)

print("Stores with non-monotonic dates:", non_monotonic_stores)

# Function to plot forecast for a given store
def plot_store_forecast(store_id, df, forecast_results):
    # Original data
    g = df[df['store'] == store_id][['date','weekly_sales']].sort_values('date')

    # Forecasted data (last 12 weeks)
    forecast = forecast_results[store_id]

    plt.figure(figsize=(12,6))

    # Plot historical sales
    plt.plot(g['date'], g['weekly_sales'], label='Historical Sales', color='blue')

    # Plot forecast line
    plt.plot(forecast.index, forecast['mean'], label='Forecast Sales', color='red')

    # Plot confidence interval
    plt.fill_between(forecast.index, forecast['mean_ci_lower'], forecast['mean_ci_upper'],
                     color='pink', alpha=0.3, label='Confidence Interval')

    plt.title(f"Store {store_id} - 12 Weeks Sales Forecast")
    plt.xlabel("Date")
    plt.ylabel("Weekly Sales")
    plt.legend()
    plt.show()

    # Example: Plot forecast for Store 20
plot_store_forecast(20, df, forecast_results)

plt.figure(figsize=(14,7))

for store in forecast_results.keys():
    # Forecast line
    f = forecast_results[store]
    plt.plot(f.index, f['mean'], label=f"Store {store}", alpha=0.6) # Use f.index for dates and 'mean' for forecast

plt.title("12 Weeks Sales Forecast - All Stores")
plt.xlabel("Date")
plt.ylabel("Forecasted Weekly Sales")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.show()

import math

stores = list(forecast_results.keys())
n = len(stores)

rows = math.ceil(n/5)  # 5 columns per row
cols = 5

fig, axes = plt.subplots(rows, cols, figsize=(20, rows*3), sharex=True, sharey=True)
axes = axes.flatten()

for i, store in enumerate(stores):
    g = df[df['store'] == store][['date','weekly_sales']].sort_values('date')
    f = forecast_results[store]

    axes[i].plot(g['date'], g['weekly_sales'], color='blue', alpha=0.6, label="Historical")
    axes[i].plot(f.index, f['mean'], color='red', label="Forecast") # Corrected column name
    axes[i].fill_between(f.index, f['mean_ci_lower'], f['mean_ci_upper'], color='pink', alpha=0.3) # Corrected column names
    axes[i].set_title(f"Store {store}")

# Remove empty subplots if any
for j in range(i+1, len(axes)):
    fig.delaxes(axes[j])

fig.suptitle("12 Weeks Sales Forecast for All Stores", fontsize=16)
plt.tight_layout(rect=[0,0,1,0.97])
plt.show()